# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AccountLocation
    from ._models_py3 import AccountPatchProperties
    from ._models_py3 import AccountProperties
    from ._models_py3 import AccountQuotaPolicyPatchProperties
    from ._models_py3 import AccountQuotaPolicyProperties
    from ._models_py3 import AccountQuotaPolicyResourceDescription
    from ._models_py3 import AccountQuotaPolicyResourceDescriptionList
    from ._models_py3 import AccountQuotaPolicyResourceDescriptionProperties
    from ._models_py3 import AccountQuotaPolicyResourcePatchDescription
    from ._models_py3 import AccountQuotaPolicyResourcePatchDescriptionProperties
    from ._models_py3 import AccountResourceDescription
    from ._models_py3 import AccountResourceDescriptionList
    from ._models_py3 import AccountResourceDescriptionProperties
    from ._models_py3 import AccountResourcePatchDescription
    from ._models_py3 import AccountResourcePatchDescriptionProperties
    from ._models_py3 import AvailableInstanceTypeDescription
    from ._models_py3 import AvailableInstanceTypeDescriptionList
    from ._models_py3 import AvailableInstanceTypeSeriesDescription
    from ._models_py3 import AvailableInstanceTypeSeriesDescriptionList
    from ._models_py3 import CheckpointPolicy
    from ._models_py3 import CheckpointRetentionPolicy
    from ._models_py3 import CompilationPolicy
    from ._models_py3 import CustomImage
    from ._models_py3 import DeploymentPolicy
    from ._models_py3 import ErrorDetailsModel
    from ._models_py3 import ErrorModel
    from ._models_py3 import ErrorModelProperties
    from ._models_py3 import FrameworkImageBase
    from ._models_py3 import GroupPolicyPatchProperties
    from ._models_py3 import GroupPolicyProperties
    from ._models_py3 import GroupPolicyResourceDescription
    from ._models_py3 import GroupPolicyResourceDescriptionList
    from ._models_py3 import GroupPolicyResourceDescriptionProperties
    from ._models_py3 import GroupPolicyResourcePatchDescription
    from ._models_py3 import GroupPolicyResourcePatchDescriptionProperties
    from ._models_py3 import InstanceTypeSeriesQuota
    from ._models_py3 import InstanceTypeSettings
    from ._models_py3 import JobPatchProperties
    from ._models_py3 import JobResourceDescription
    from ._models_py3 import JobResourceDescriptionList
    from ._models_py3 import JobResourceDescriptionProperties
    from ._models_py3 import JobResourcePatchDescription
    from ._models_py3 import JobResourcePatchDescriptionProperties
    from ._models_py3 import JobResourceProperties
    from ._models_py3 import JobSasTokenDescription
    from ._models_py3 import JobUserActionDescription
    from ._models_py3 import PlacementPolicy
    from ._models_py3 import PyTorchFrameworkImage
    from ._models_py3 import Resource
    from ._models_py3 import ResourceSystemData
    from ._models_py3 import ScalePolicy
    from ._models_py3 import StorageContainerProperties
    from ._models_py3 import StorageContainerResourceDescription
    from ._models_py3 import StorageContainerResourceDescriptionList
    from ._models_py3 import StorageContainerResourceDescriptionProperties
    from ._models_py3 import StorageContainerResourcePatchDescription
    from ._models_py3 import StorageContainerResourcePatchDescriptionProperties
    from ._models_py3 import StorageLocation
    from ._models_py3 import StorageMount
    from ._models_py3 import StorageSourceAzureAiSupercomputerStorage
    from ._models_py3 import StorageSourceAzureBlob
    from ._models_py3 import StorageSourceAzureFile
    from ._models_py3 import StorageSourceBase
    from ._models_py3 import TensorFlowFrameworkImage
    from ._models_py3 import TrackedResource
except (SyntaxError, ImportError):
    from ._models import AccountLocation  # type: ignore
    from ._models import AccountPatchProperties  # type: ignore
    from ._models import AccountProperties  # type: ignore
    from ._models import AccountQuotaPolicyPatchProperties  # type: ignore
    from ._models import AccountQuotaPolicyProperties  # type: ignore
    from ._models import AccountQuotaPolicyResourceDescription  # type: ignore
    from ._models import AccountQuotaPolicyResourceDescriptionList  # type: ignore
    from ._models import AccountQuotaPolicyResourceDescriptionProperties  # type: ignore
    from ._models import AccountQuotaPolicyResourcePatchDescription  # type: ignore
    from ._models import AccountQuotaPolicyResourcePatchDescriptionProperties  # type: ignore
    from ._models import AccountResourceDescription  # type: ignore
    from ._models import AccountResourceDescriptionList  # type: ignore
    from ._models import AccountResourceDescriptionProperties  # type: ignore
    from ._models import AccountResourcePatchDescription  # type: ignore
    from ._models import AccountResourcePatchDescriptionProperties  # type: ignore
    from ._models import AvailableInstanceTypeDescription  # type: ignore
    from ._models import AvailableInstanceTypeDescriptionList  # type: ignore
    from ._models import AvailableInstanceTypeSeriesDescription  # type: ignore
    from ._models import AvailableInstanceTypeSeriesDescriptionList  # type: ignore
    from ._models import CheckpointPolicy  # type: ignore
    from ._models import CheckpointRetentionPolicy  # type: ignore
    from ._models import CompilationPolicy  # type: ignore
    from ._models import CustomImage  # type: ignore
    from ._models import DeploymentPolicy  # type: ignore
    from ._models import ErrorDetailsModel  # type: ignore
    from ._models import ErrorModel  # type: ignore
    from ._models import ErrorModelProperties  # type: ignore
    from ._models import FrameworkImageBase  # type: ignore
    from ._models import GroupPolicyPatchProperties  # type: ignore
    from ._models import GroupPolicyProperties  # type: ignore
    from ._models import GroupPolicyResourceDescription  # type: ignore
    from ._models import GroupPolicyResourceDescriptionList  # type: ignore
    from ._models import GroupPolicyResourceDescriptionProperties  # type: ignore
    from ._models import GroupPolicyResourcePatchDescription  # type: ignore
    from ._models import GroupPolicyResourcePatchDescriptionProperties  # type: ignore
    from ._models import InstanceTypeSeriesQuota  # type: ignore
    from ._models import InstanceTypeSettings  # type: ignore
    from ._models import JobPatchProperties  # type: ignore
    from ._models import JobResourceDescription  # type: ignore
    from ._models import JobResourceDescriptionList  # type: ignore
    from ._models import JobResourceDescriptionProperties  # type: ignore
    from ._models import JobResourcePatchDescription  # type: ignore
    from ._models import JobResourcePatchDescriptionProperties  # type: ignore
    from ._models import JobResourceProperties  # type: ignore
    from ._models import JobSasTokenDescription  # type: ignore
    from ._models import JobUserActionDescription  # type: ignore
    from ._models import PlacementPolicy  # type: ignore
    from ._models import PyTorchFrameworkImage  # type: ignore
    from ._models import Resource  # type: ignore
    from ._models import ResourceSystemData  # type: ignore
    from ._models import ScalePolicy  # type: ignore
    from ._models import StorageContainerProperties  # type: ignore
    from ._models import StorageContainerResourceDescription  # type: ignore
    from ._models import StorageContainerResourceDescriptionList  # type: ignore
    from ._models import StorageContainerResourceDescriptionProperties  # type: ignore
    from ._models import StorageContainerResourcePatchDescription  # type: ignore
    from ._models import StorageContainerResourcePatchDescriptionProperties  # type: ignore
    from ._models import StorageLocation  # type: ignore
    from ._models import StorageMount  # type: ignore
    from ._models import StorageSourceAzureAiSupercomputerStorage  # type: ignore
    from ._models import StorageSourceAzureBlob  # type: ignore
    from ._models import StorageSourceAzureFile  # type: ignore
    from ._models import StorageSourceBase  # type: ignore
    from ._models import TensorFlowFrameworkImage  # type: ignore
    from ._models import TrackedResource  # type: ignore

from ._ai_supercomputer_management_client_enums import (
    AccountStatus,
    CheckpointRetentionMode,
    CompilationMode,
    FrameworkKind,
    IdleResourcesHandlingMode,
    JobStatus,
    ParallelismStrategy,
    PolicyStatus,
    ProtocolType,
    ProvisioningState,
    SchedulingMode,
    SchedulingPriority,
    StorageContainerStatus,
    StorageContainerTier,
    StorageSourceKind,
)

__all__ = [
    'AccountLocation',
    'AccountPatchProperties',
    'AccountProperties',
    'AccountQuotaPolicyPatchProperties',
    'AccountQuotaPolicyProperties',
    'AccountQuotaPolicyResourceDescription',
    'AccountQuotaPolicyResourceDescriptionList',
    'AccountQuotaPolicyResourceDescriptionProperties',
    'AccountQuotaPolicyResourcePatchDescription',
    'AccountQuotaPolicyResourcePatchDescriptionProperties',
    'AccountResourceDescription',
    'AccountResourceDescriptionList',
    'AccountResourceDescriptionProperties',
    'AccountResourcePatchDescription',
    'AccountResourcePatchDescriptionProperties',
    'AvailableInstanceTypeDescription',
    'AvailableInstanceTypeDescriptionList',
    'AvailableInstanceTypeSeriesDescription',
    'AvailableInstanceTypeSeriesDescriptionList',
    'CheckpointPolicy',
    'CheckpointRetentionPolicy',
    'CompilationPolicy',
    'CustomImage',
    'DeploymentPolicy',
    'ErrorDetailsModel',
    'ErrorModel',
    'ErrorModelProperties',
    'FrameworkImageBase',
    'GroupPolicyPatchProperties',
    'GroupPolicyProperties',
    'GroupPolicyResourceDescription',
    'GroupPolicyResourceDescriptionList',
    'GroupPolicyResourceDescriptionProperties',
    'GroupPolicyResourcePatchDescription',
    'GroupPolicyResourcePatchDescriptionProperties',
    'InstanceTypeSeriesQuota',
    'InstanceTypeSettings',
    'JobPatchProperties',
    'JobResourceDescription',
    'JobResourceDescriptionList',
    'JobResourceDescriptionProperties',
    'JobResourcePatchDescription',
    'JobResourcePatchDescriptionProperties',
    'JobResourceProperties',
    'JobSasTokenDescription',
    'JobUserActionDescription',
    'PlacementPolicy',
    'PyTorchFrameworkImage',
    'Resource',
    'ResourceSystemData',
    'ScalePolicy',
    'StorageContainerProperties',
    'StorageContainerResourceDescription',
    'StorageContainerResourceDescriptionList',
    'StorageContainerResourceDescriptionProperties',
    'StorageContainerResourcePatchDescription',
    'StorageContainerResourcePatchDescriptionProperties',
    'StorageLocation',
    'StorageMount',
    'StorageSourceAzureAiSupercomputerStorage',
    'StorageSourceAzureBlob',
    'StorageSourceAzureFile',
    'StorageSourceBase',
    'TensorFlowFrameworkImage',
    'TrackedResource',
    'AccountStatus',
    'CheckpointRetentionMode',
    'CompilationMode',
    'FrameworkKind',
    'IdleResourcesHandlingMode',
    'JobStatus',
    'ParallelismStrategy',
    'PolicyStatus',
    'ProtocolType',
    'ProvisioningState',
    'SchedulingMode',
    'SchedulingPriority',
    'StorageContainerStatus',
    'StorageContainerTier',
    'StorageSourceKind',
]
