# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import TYPE_CHECKING

from azure.mgmt.core import ARMPipelineClient
from msrest import Deserializer, Serializer

if TYPE_CHECKING:
    # pylint: disable=unused-import,ungrouped-imports
    from typing import Any, Optional

    from azure.core.credentials import TokenCredential

from ._configuration import AISupercomputerManagementClientConfiguration
from .operations import AccountQuotaPolicyOperations
from .operations import AccountOperations
from .operations import GroupPolicyOperations
from .operations import InstanceTypeSeriesOperations
from .operations import JobOperations
from .operations import StorageContainerOperations
from . import models


class AISupercomputerManagementClient(object):
    """AISupercomputer Management Client.

    :ivar account_quota_policy: AccountQuotaPolicyOperations operations
    :vartype account_quota_policy: ai_supercomputer_management_client.operations.AccountQuotaPolicyOperations
    :ivar account: AccountOperations operations
    :vartype account: ai_supercomputer_management_client.operations.AccountOperations
    :ivar group_policy: GroupPolicyOperations operations
    :vartype group_policy: ai_supercomputer_management_client.operations.GroupPolicyOperations
    :ivar instance_type_series: InstanceTypeSeriesOperations operations
    :vartype instance_type_series: ai_supercomputer_management_client.operations.InstanceTypeSeriesOperations
    :ivar job: JobOperations operations
    :vartype job: ai_supercomputer_management_client.operations.JobOperations
    :ivar storage_container: StorageContainerOperations operations
    :vartype storage_container: ai_supercomputer_management_client.operations.StorageContainerOperations
    :param credential: Credential needed for the client to connect to Azure.
    :type credential: ~azure.core.credentials.TokenCredential
    :param subscription_id: The customer subscription identifier.
    :type subscription_id: str
    :param str base_url: Service URL
    :keyword int polling_interval: Default waiting time between two polls for LRO operations if no Retry-After header is present.
    """

    def __init__(
        self,
        credential,  # type: "TokenCredential"
        subscription_id,  # type: str
        base_url=None,  # type: Optional[str]
        **kwargs  # type: Any
    ):
        # type: (...) -> None
        if not base_url:
            base_url = 'https://management.azure.com'
        self._config = AISupercomputerManagementClientConfiguration(credential, subscription_id, **kwargs)
        self._client = ARMPipelineClient(base_url=base_url, config=self._config, **kwargs)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)

        self.account_quota_policy = AccountQuotaPolicyOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.account = AccountOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.group_policy = GroupPolicyOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.instance_type_series = InstanceTypeSeriesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.job = JobOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.storage_container = StorageContainerOperations(
            self._client, self._config, self._serialize, self._deserialize)

    def close(self):
        # type: () -> None
        self._client.close()

    def __enter__(self):
        # type: () -> AISupercomputerManagementClient
        self._client.__enter__()
        return self

    def __exit__(self, *exc_details):
        # type: (Any) -> None
        self._client.__exit__(*exc_details)
